const data={score:38,state:"WATCH",delta:"▲ +2 / 24H",confidence:84,assessment:"Current global risk remains stable despite concentrated military activity in East Asia. Escalation signals remain limited.",event:{title:"Taiwan Strait activity monitored",body:"Military movement remains the strongest risk driver in the current cycle.",source:"Reuters"},ranking:[{name:"Ukraine",score:72,move:"▲ +2",bar:72},{name:"Taiwan",score:68,move:"▲ +4",bar:68},{name:"Iran",score:64,move:"→ 0",bar:64},{name:"Russia",score:61,move:"▼ -1",bar:61},{name:"Israel",score:58,move:"▲ +1",bar:58}]};
const $=id=>document.getElementById(id);
function jst(){return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit'}).format(new Date())}
function render(){
 $('score').textContent=data.score;$('state').textContent=data.state;$('delta').textContent=data.delta;$('updated').textContent=`UPDATED — ${jst()} JST`;$('assessment').textContent=data.assessment;$('confidence').textContent=data.confidence+'%';$('eventTitle').textContent=data.event.title;$('eventBody').textContent=data.event.body;
 $('rankingList').innerHTML=data.ranking.map((r,i)=>`<div class="rank"><div class="ranknum">${String(i+1).padStart(2,'0')}</div><div><div class="rankname">${r.name}</div><div class="rankmeta">${r.move}</div></div><div class="rankscore">${r.score}</div><div class="rankbar"><i style="width:${r.bar}%"></i></div></div>`).join('');
 if(new URLSearchParams(location.search).get('admin')==='doom') $('admin').classList.add('open');
}
function makePost(type){const top=data.ranking.slice(0,3).map(x=>x.name).join(' / ');const tag='#ORACLE #WorldRisk #GlobalRisk #Geopolitics #WorldNews #RiskIntelligence';const lines={morning:`ORACLE Morning Brief\n\nGlobal Risk Index: ${data.score} (${data.state})\n24H: ${data.delta}\n\nPrimary concern: ${data.event.title}\nTop risk regions: ${top}\n\n${tag}`,noon:`ORACLE Midday Signal\n\nGlobal risk remains ${data.state}.\nIndex: ${data.score}\n\nAI Assessment:\n${data.assessment}\n\n${tag}`,night:`ORACLE Daily Close\n\nGlobal Risk Index closed at ${data.score}.\nTop regions: ${top}\n\nNo evidence of immediate global escalation detected.\n\n${tag}`,alert:`ORACLE Alert\n\nRisk movement detected.\nIndex: ${data.score}\nPrimary event: ${data.event.title}\n\nMonitor updates.\n\n${tag}`};$('postText').value=lines[type]||lines.noon}
function copyPost(){navigator.clipboard?.writeText($('postText').value);alert('Copied')}
render();
