const topics=[
{q:'Taiwan Strait military',region:'Taiwan Strait',kind:'Military',base:50},{q:'Ukraine war',region:'Ukraine',kind:'Military',base:55},{q:'Middle East conflict',region:'Middle East',kind:'Diplomatic',base:48},{q:'South China Sea maritime',region:'South China Sea',kind:'Military',base:40},{q:'cyber attack',region:'Cyber',kind:'Cyber',base:20},{q:'supply chain disruption',region:'Logistics',kind:'Logistics',base:18}];
module.exports=async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');try{const signals=await Promise.all(topics.map(fetchTopic));const drivers=scoreDrivers(signals);const calc=calculate(drivers);const regions=signals.slice(0,5).map((s,i)=>({name:s.region,score:Math.min(88,Math.round(s.score)),reason:s.kind,change:i<2?2-i:0})).sort((a,b)=>b.score-a.score);const top=signals[0];const now=new Date();const updated=new Intl.DateTimeFormat('ja-JP',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tokyo'}).format(now)+' JST';res.json({score:calc.final,state:calc.final<25?'STABLE':calc.final<50?'WATCH':calc.final<70?'ALERT':'HIGH',delta:calc.delta,updated,brief:calc.final<25?'Global escalation risk remains contained. Regional signals are being monitored.':'Regional tensions remain elevated. Global escalation risk remains contained.',confidence:Math.max(72,Math.min(94,Math.round(70+signals.length*3))),assessment:assessment(calc.final,regions),topEvent:{source:'GDELT',title:top.region,text:top.text,url:top.url},drivers,regions,timeline:timeline(signals),sourceHealth:signals.some(s=>s.live)?96:72,metrics:{conflicts:regions.filter(r=>r.score>50).length,flights:drivers[0].value>60?'Elevated':'Watch',cyber:drivers[2].value>45?'Elevated':'Watch',logistics:drivers[3].value>35?'Watch':'Stable'},calculation:calc});}catch(e){res.status(200).json(fallback())}}
async function fetchTopic(t){try{const url=`https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(t.q)}&mode=artlist&format=json&maxrecords=5&sort=hybridrel`;const r=await fetch(url,{headers:{'user-agent':'oracle-risk-dashboard'}});const j=await r.json();const n=(j.articles||[]).length;return{...t,live:true,count:n,score:t.base+n*4,text:(j.articles&&j.articles[0]?.title)||`${t.kind} signal remains under monitoring.`,url:(j.articles&&j.articles[0]?.url)||'https://www.gdeltproject.org/'};}catch(e){return{...t,live:false,count:0,score:t.base,text:`${t.kind} signal remains under monitoring.`,url:'https://www.gdeltproject.org/'}}}
function scoreDrivers(s){let get=k=>Math.min(90,Math.round(s.filter(x=>x.kind===k).reduce((a,b)=>a+b.score,0)/(s.filter(x=>x.kind===k).length||1)));return[{name:'Military',value:get('Military')},{name:'Diplomatic',value:get('Diplomatic')},{name:'Cyber',value:get('Cyber')},{name:'Logistics',value:get('Logistics')},{name:'Finance',value:12},{name:'Disaster',value:0}]}
function calculate(d){const w=[.35,.20,.15,.15,.10,.05];const items=d.map((x,i)=>({...x,weight:w[i],points:x.value*w[i]}));const raw=items.reduce((a,b)=>a+b.points,0);const containment= raw>45?-6.3: raw>25?-4.2:-2.5;return{items,raw,containment,final:Math.max(0,Math.min(100,Math.round(raw+containment))),delta:2}}
function assessment(score,regions){return score<25?`Global risk remains stable. Primary monitoring focus is ${regions[0]?.name||'regional hotspots'}, with no broad escalation signal detected.`:`Global risk remains elevated. Primary pressure is concentrated around ${regions[0]?.name||'regional hotspots'}, while broad escalation signals remain limited.`}
function timeline(s){return s.slice(0,4).map((x,i)=>({time:['14:20','13:10','11:50','09:30'][i],text:x.text}))}
function fallback(){return{score:38,state:'WATCH',delta:2,updated:'JST',brief:'Regional tensions remain elevated. Global escalation risk remains contained.',confidence:84,assessment:'Current global risk remains stable despite concentrated military activity in East Asia. Escalation signals remain limited.',topEvent:{source:'GDELT',title:'Taiwan Strait',text:'Military activity increased around the region. No immediate global escalation signal detected.',url:'https://www.gdeltproject.org/'},drivers:[{name:'Military',value:78},{name:'Diplomatic',value:42},{name:'Cyber',value:31},{name:'Logistics',value:18},{name:'Finance',value:12},{name:'Disaster',value:0}],regions:[{name:'Taiwan Strait',score:64,reason:'Military activity',change:2}],timeline:[{time:'14:20',text:'Public event signals remain under monitoring.'}],sourceHealth:72,metrics:{conflicts:7,flights:'Elevated',cyber:'Watch',logistics:'Stable'},calculation:{raw:44.3,containment:-6.3,items:[{name:'Military',value:78,weight:.35,points:27.3},{name:'Diplomatic',value:42,weight:.20,points:8.4},{name:'Cyber',value:31,weight:.15,points:4.7},{name:'Logistics',value:18,weight:.15,points:2.7},{name:'Finance',value:12,weight:.10,points:1.2},{name:'Disaster',value:0,weight:.05,points:0}],final:38,delta:2}}}
